torch_settings:
  device: cuda

behaviors:
  Wolf1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 0.0005
      beta: 0.005
      beta_schedule: linear
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        learning_rate: 3.0e-4
    max_steps: 5000000
    time_horizon: 512
    summary_freq: 10000

  Wolf2:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 0.0005
      beta: 0.005
      beta_schedule: linear
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        learning_rate: 3.0e-4
    max_steps: 5000000
    time_horizon: 512
    summary_freq: 10000

environment_parameters:
  rewards: 0.0 # base-time-coop e.g: 127
  isLLM: 0 # 0: Distance reward / 1: LLM reward
  behavior_target: 0 # 0: Wolf / 1: Deer
  randomness: 0 # 0: fixed wall size/ 1 : random wall size
  wall_size:
    curriculum:
      - name: lesson0
        value: 0.2
        completion_criteria:
          measure: reward
          behavior: Wolf1
          threshold: 0.8
          signal_smoothing: true
          min_lesson_length: 500
      - name: lesson1
        value: 0.3
        completion_criteria:
          measure: reward
          behavior: Wolf1
          threshold: 0.8
          signal_smoothing: true
          min_lesson_length: 500
      - name: lesson2
        value: 0.4
        completion_criteria:
          measure: reward
          behavior: Wolf1
          threshold: 0.7
          signal_smoothing: true
          min_lesson_length: 500
      - name: lesson3
        value: 0.5
        completion_criteria:
          measure: reward
          behavior: Wolf1
          threshold: 0.7
          signal_smoothing: true
          min_lesson_length: 500
      - name: lesson4
        value: 0.6
        completion_criteria:
          measure: reward
          behavior: Wolf1
          threshold: 0.7
          signal_smoothing: true
          min_lesson_length: 500
      - name: lesson5
        value: 0.7
        completion_criteria:
          measure: reward
          behavior: Wolf1
          threshold: 0.7
          signal_smoothing: true
          min_lesson_length: 500
      - name: lesson6
        value: 0.8
        completion_criteria:
          measure: reward
          behavior: Wolf1
          threshold: 0.7
          signal_smoothing: true
          min_lesson_length: 500
      - name: lesson7
        value: 0.9
        completion_criteria:
          measure: reward
          behavior: Wolf1
          threshold: 0.7
          signal_smoothing: true
          min_lesson_length: 500
      - name: lesson8
        value: 1.0
